name: Build docs
on:
  # Build PRs 
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'

  # On push event
  push:
    # Build only changes pushed into the `master` branch -- avoids double builds when you push in a branch which has a PR.
    branches:
      - master
      - pipeline
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'

  workflow_dispatch:

permissions:
  statuses: write

env:
  REPOSITORY: ${{ github.repository }}
  IS_FORK: ${{ github.repository != vars.CURRENT_REPO }}
  IS_PR: ${{ github.event_name == 'pull_request' }}
  EVENT_NAME: ${{ toJSON(github.event_name) }}
  # format: username:branch
  PR_HEAD_LABEL: ${{ toJSON(github.event.pull_request.head.label) }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  docs:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != vars.CURRENT_REPO && 'external-collaborators' || '' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
