on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

name: Prepare release

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # https://github.com/googleapis/release-please/blob/main/src/changelog-notes.ts#L42
          command: manifest
          # This is required to avoid `release-please failed: API rate limit exceeded for installation ID XYZ`
          token: ${{ secrets.GITHUB_TOKEN }}
